<?php
include "ketnoi.php";
$sql = "CREATE TABLE SanPham (
TenSP VARCHAR(100) PRIMARY KEY, 
DonGia DECIMAL(8,0) NOT NULL, 
SoLuong TINYINT NOT NULL,
IDHang VARCHAR(10) NOT NULL,
MoTa VARCHAR(1000) NOT NULL,
Ram VARCHAR(10) NOT NULL,
DungLuong VARCHAR(10) NOT NULL,
ManHinh VARCHAR(100) NOT NULL,
CameraT VARCHAR(20) NOT NULL,
CameraS VARCHAR(20) NOT NULL,
CPU VARCHAR(1000) NOT NULL,
Pin VARCHAR(10) NOT NULL,
SacNhanh VARCHAR(10) NOT NULL,
HDH VARCHAR(10) NOT NULL,
Anh1 VARCHAR(100) NOT NULL,
Anh2 VARCHAR(100) NOT NULL,
Anh3 VARCHAR(100) NOT NULL,
Anh4 VARCHAR(100) NOT NULL,
Anh5 VARCHAR(100) NOT NULL,
CONSTRAINT SP_Hang FOREIGN KEY (IDHang) REFERENCES Hang(IDHang) ON DELETE CASCADE ON UPDATE CASCADE
)";
$conn->exec($sql);
echo "Tạo bảng thành công!";
$conn = null;
?>
